### PR TITLE
Logic bug fix : when capturing a stone, check if it's opponent's stone

### PR DESCRIPTION
**Pull request by ihavnoid**
Without checking the color of captured stones, it can capture its own stone when the newly added move makes its own liberty to be zero.

### CODE REVIEW

**Comment by fsparv** [comment]
Thx I'll review this early next week.

**Comment by fsparv** [comment]
The problem with your fix is it implies that isLegalMove() returned true for a self capture, which I don't think it's supposed to do. I suppose if I ever want to handle rule sets that allow self capture I need this, but I want to figure out the underlying problem instead.

**Comment by ihavnoid** [comment]
I was not aware that you wanted to implement self-capture.  However, if you wanted to implement self-capture, then still the capture logic has to change, probably something like this pseudocode

opponent_stone_captured=false;
foreach(adjacent opponent stone) {
    if(liberty == 0) {
        capture(opponent_stone); opponent_stone_captured = true;
    }
}
if(!opponent_stone_captured and newly_played_stone_has_zero_liberty) {
   capture(newly_played_stone);
}

That is, the newly played stone may result in both stones having zero liberty.  In that case, it should remove opponent stones only.  This was the bug that I observed - when the newly played stone was part of a group that turned to zero liberty, but also had another opponent group turn to zero liberty, sometimes it worked out as self-capture, other times it turned into a normal capture.

**Comment by fsparv** [comment]
I'm sorry, let me clarify.... rulesImp.isLegalMove() is where self capture is *already* checked. SimpleRules the move should not be legal if it is self capture in the current implementation. In a future implementation (a NewZelandRules or IngRules perhaps) this could be legal. All decisions about legality of a move must occur in the rules class. 

I think that you are proposing that the bug is that the rules declare the move legal because something of the opponent's is meant to be captured, but the first direction that is checked is part of the capturing group (also out of liberties). 

This might be a problem, but the decision to capture self or not has to reside within the rules impl, since sometimes it's legal and sometimes it is not depending on the rule set.

I hope to write a unit test reproducing the issue so that I can verify that the fix really fixes something. 15 years ago I had no idea what a unit test was, so I didn't write any, but now I know better :) if there's one area of the code that should be made testable it's the rules & capturing logic.

**Comment by nsoft** [comment]
Thanks for your help. The fix you proposed was mostly correct but I just wanted to be a bit more pedantic  about things and add some capabilities to write unit tests :)

**Comment by nsoft** [comment]
Oh and in case you haven't figured it out this is also fsparv (when I forget to switch accounts from my work stuff) ;)

**Pull request merged**
