### PR TITLE
changed regex for AutoGTP v11

### PR DESCRIPTION
**Pull request by ltp27**
added AutoGTPv11 format

### CODE REVIEW

**Comment by barrybecker4** [comment]
I tried this, but I don't think it works for v11.
I got this error
```
      Move:B H8
oh noes!!!
```
I don't think that the B is expected. The regexp should be modified so that the part that matches the optional color is outside the ()'s. I'll try making a PR.

**Comment by ltp27** [comment]
i uploaded wrong one.
now this will work

**Comment by barrybecker4** [comment]
OK. I just opened a PR too. I guess @fsparv can pick either one, but they are not identical.

**Comment by fsparv** [comment]
Although this was first and is arguably less brittle, I took the other pull request because I decided to favor readability of the regex. Thanks however for your contribution. Sorry it took me so long to get to this.

**Pull request closed without merging**
